version: "3" 

services:
  podimo:
    image: sauerhosen/thijstool:latest # voor Raspberry Pi en andere ARM systemen
    # image: sauerhosen/thijstool:amd64-latest # voor Intel/AMD systemen
    container_name: podimo
    environment:
      - PODIMO_HOSTNAME=podimo.jouwdomeinnaam.nl # Vul je IP adres of domeinnaam in
      - PODIMO_BIND_HOST=0.0.0.0:12104 # Laat dit staan (tenzij je weet wat je doet)
      - ZENROWS_API_KEY=jouw_api_key # Vul hier je Zenrows API key in
      - PODCAST_CACHE_TIME=21600 # 21600 seconden = 6 uur.  
      - DEBUG=true # Debug aan of uit
      - PODIMO_PROTOCOL=https # what protocol is being used for all links that are displayed to the user. 
    ports:
      - 12104:12104 # Laat staan, tenzij je weet wat je doet. Wijzig de port (bijv in 443 als je de Thijstool zonder poort toevoeging (ip-adres:portnr) wil benaderen). 
    restart: unless-stopped    